# Generated by Django 4.1 on 2022-09-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='vote',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
